### ISSUE TITLE
Bug #4: When player 2 joins the match, the character stats are displayed as 0. 

### ISSUE THREAD

**Issue by TinkLyke** [lawlbit/GameNamePlaceHolder#58]

**Comment by SusanSuY** [comment]
**Root cause:** The stat allocations were being updated on the server correctly, but the update stat text function was being called too early before the information on networking finished sending.

**Solution:** Move updating of stat text to Update() function. Fixed in [c923b6e](https://github.com/lawlbit/GameNamePlaceHolder/commit/c923b6e8b7ab9ad944225b9c42a1d04b1e82f48d).
